### ISSUE TITLE
마켓 관련 API 명세 작성하기

### ISSUE THREAD

**Issue by owel-dev** [Team-Snacks/Snacks-Ninja#35]
### 해야할 일

1. 마켓에 등록된 위젯 목록 가져오는 API 구현.
2. 마켓에 위젯을 추가하는 API 구현.

**Comment by scarf005** [comment]
1번과 2번의 API 명세 (엔드포인트, 바디, 메소드)가 궁금합니다

**Comment by owel-dev** [comment]
**GET /market** 마켓의 위젯 목록 받아오기
```
[
	{ 
		name: “widget1”
	},
	{
		name: “widget2”
	} 
]
```

**POST /market** 마켓에 위젯 추가하기.
```
{ 
	name: “widget1”
}
```

**Comment by scarf005** [comment]
배열 형태 (`[ "widget1", "widget2", ... ]`)가 아닌 오브젝트 형태 (`{ "name": "widget1" }`) 로 추가하신 것은 다른 정보를 추가하는 것을 대비하기 위해서인 거죠?

**Comment by owel-dev** [comment]
@scarf005 넵 맞습니다! 이름 외의 정보가 추가될 것을 염두해 두었습니다.

**Comment by scarf005** [comment]
좋습니다. 모두 동의한다면 완료로 닫아도 될 것 같습니다.

**Comment by jyhyun97** [comment]
확인했습니다!

**Comment by dlwndms0812** [comment]
확인했습니다.
